### ISSUE TITLE
Calling reload from the console occasionally causes a crash

### ISSUE THREAD

**Issue by slowriot** [CanaryModTeam/CanaryMod#148]
```
2014-12-10 12:06:41 [INFO] Reloading configurations ...
2014-12-10 12:06:41 [ERROR] Encountered an unexpected exception
net.canarymod.api.world.UnknownWorldException: World default is unknown. Autoload was enabled for this call.
        at net.canarymod.api.world.CanaryWorldManager.getWorld(CanaryWorldManager.java:128) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.canarymod.api.CanaryServer.getDefaultWorld(CanaryServer.java:433) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.management.ServerConfigurationManager.q(ServerConfigurationManager.java:1029) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10$
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1049) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.a(DedicatedServer.java:384) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.profiler.PlayerUsageSnooper.b(PlayerUsageSnooper.java:100) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.u(MinecraftServer.java:557) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:430) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer$3.run(MinecraftServer.java:742) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
2014-12-10 12:06:41 [ERROR] This crash report has been saved to: /home/minecraft/./crash-reports/crash-2014-12-10_12.06.41-server.txt
2014-12-10 12:06:41 [INFO] Stopping server
```
Full crash dump in http://pastebin.com/bbwzUwQb

**Comment by darkdiplomat** [comment]
1.7.10 Builds are no longer being worked on by the team.
