### ISSUE TITLE
Server crash with ConcurrentModificationException on ticking entity

### ISSUE THREAD

**Issue by slowriot** [CanaryModTeam/CanaryMod#149]
```
2014-12-11 18:00:02 [ERROR] Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:609) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.v(DedicatedServer.java:367) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.u(MinecraftServer.java:526) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:430) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer$3.run(MinecraftServer.java:742) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(Unknown Source) ~[?:1.7.0_11]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.7.0_11]
        at net.minecraft.entity.EntityTracker.a(EntityTracker.java:261) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.entity.player.EntityPlayerMP.h(EntityPlayerMP.java:271) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.world.World.a(World.java:1350) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.world.WorldServer.a(WorldServer.java:495) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.world.World.g(World.java:1330) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.world.World.h(World.java:1228) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.world.WorldServer.h(WorldServer.java:365) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:604) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
        ... 4 more
```
Not clear what events led up to this; everyone online claims they were doing nothing unusual at the time.

Full crash report:
http://pastebin.com/GH1n6r7c

**Comment by darkdiplomat** [comment]
1.7.10 Builds are no longer being worked on by the team.
