### ISSUE TITLE
refreshRow() called on row that has been deleted or had primary key changed

### ISSUE THREAD

**Issue by slowriot** [CanaryModTeam/CanaryMod#152]
In some cases the canary database is modified outside of minecraft (modifying player permissions etc); occasionally when that happens this exception is thrown in the console.
```
[SERVER] 2014-12-18 20:22:35 [ERROR] refreshRow() called on row that has been deleted or had primary key changed.
[SERVER] java.sql.SQLException: refreshRow() called on row that has been deleted or had primary key changed.
[SERVER]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mysql.jdbc.UpdatableResultSet.refreshRow(UpdatableResultSet.java:1388) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mysql.jdbc.UpdatableResultSet.refreshRow(UpdatableResultSet.java:1306) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2405) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at com.mchange.v2.c3p0.impl.NewProxyResultSet.updateRow(NewProxyResultSet.java:1958) ~[CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at net.canarymod.database.mysql.MySQLDatabase.update(MySQLDatabase.java:118) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at net.canarymod.backbone.BackbonePermissions.updatePermission(BackbonePermissions.java:370) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
[SERVER]        at net.canarymod.backbone.BackbonePermissions.addPermission(BackbonePermissions.java:312) [CanaryMod-1.7.10-1.1.3-20141119.185316-43-shaded.jar:1.7.10-1.1.3-SNAPSHOT]
```

**Comment by slowriot** [comment]
Do you actually fix any of the issues you close? If so, where's the associated changeset?

**Comment by darkdiplomat** [comment]
I was in the process of moving the issue to the Lib's tracker and got sidetracked before doing so
