### ISSUE TITLE
ReportedException periodically fires

### ISSUE THREAD

**Issue by kdbanman** [CanaryModTeam/CanaryMod#158]
Has happened with zero players online, and with one player online.  Nobody was doing anything.  Server does not go down.

```
> net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.e(Entity.java:1092)
	at net.minecraft.entity.Entity.d(Entity.java:1052)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.a(AnvilChunkLoader.java:227)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.a(AnvilChunkLoader.java:99)
	at net.minecraft.world.gen.ChunkProviderServer.b(ChunkProviderServer.java:207)
	at net.minecraft.world.gen.ChunkProviderServer.a(ChunkProviderServer.java:240)
	at net.minecraft.world.WorldServer.a(WorldServer.java:609)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:329)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:314)
	at net.minecraft.server.MinecraftServer.u(MinecraftServer.java:555)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at net.minecraft.server.MinecraftServer$3.run(MinecraftServer.java:753)
Caused by: java.lang.NullPointerException
	at net.minecraft.village.MerchantRecipe.i(MerchantRecipe.java:100)
	at net.minecraft.village.MerchantRecipeList.a(MerchantRecipeList.java:96)
	at net.minecraft.entity.passive.EntityVillager.b(EntityVillager.java:163)
	at net.minecraft.entity.Entity.e(Entity.java:1075)
	... 11 more
```

**Comment by darkdiplomat** [comment]
1.7.10 is no longer under active development
