### ISSUE TITLE
NoSuchFieldError when running stop command at EULA prompt

### ISSUE THREAD

**Issue by tuxillator** [CanaryModTeam/CanaryMod#170]
Seeing a NoSuchFieldError if I run `stop` at the prompt to go and accept the EULA. Ctrl-C exits normally. If I set eula.txt and rerun, `stop` works normally.
```
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Please wait while the libraries initialize...
Starting: CanaryMod 1.8.0-1.2.0-SNAPSHOT
Canary Path: /home/jeff/serverroot/servers/canarytest/canarymod.jar & Working From: /home/jeff/serverroot/servers/canarytest
Could not find the server configuration at config/server.cfg, creating default.
Could not find the database configuration at config/db.cfg, creating default.
Registered xml Database
Could not find config/ops.cfg. Creating one for you...
You can now add ops to config/ops.cfg (one per line!). We left you a note.
Failed to scan for plugins. 'plugins/' is not a directory. Creating...
[22:54:23] [CanaryMod] [INFO]: Starting: CanaryMod 1.8.0-1.2.0-SNAPSHOT
[22:54:23] [CanaryMod] [INFO]: Canary Path: /home/jeff/serverroot/servers/canarytest/canarymod.jar & Working From: /home/jeff/serverroot/servers/canarytest
[22:54:23] [CanaryMod] [INFO]: Could not find the server configuration at config/server.cfg, creating default.
[22:54:23] [CanaryMod] [INFO]: Could not find the database configuration at config/db.cfg, creating default.
[22:54:23] [CanaryMod] [INFO]: Registered xml Database
[22:54:24] [CanaryMod] [INFO]: Could not find config/ops.cfg. Creating one for you...
[22:54:24] [CanaryMod] [INFO]: You can now add ops to config/ops.cfg (one per line!). We left you a note.
[22:54:24] [CanaryMod] [WARN]: Failed to scan for plugins. 'plugins/' is not a directory. Creating...
[22:54:25] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: Starting minecraft server version 1.8
[22:54:25] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: Loading properties
[22:54:25] [net.minecraft.server.ServerEula] [WARN]: Failed to load eula.txt
[22:54:25] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.
> stop
[22:54:35] [net.minecraft.server.MinecraftServer] [INFO]: An unknown error occurred while attempting to perform this command
[22:54:35] [net.minecraft.command.CommandHandler] [ERROR]: Couldn't process command: 'stop'
java.lang.NoSuchFieldError: c
        at net.minecraft.command.server.CommandStop.a(CommandStop.java:21) ~[canarymod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.command.CommandHandler.a(CommandHandler.java:86) [canarymod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.command.CommandHandler.a(CommandHandler.java:67) [canarymod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.CanaryServer.consoleCommand(CanaryServer.java:171) [canarymod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:139) [canarymod.jar:1.8.0-1.2.0-SNAPSHOT]
```

**Comment by tuxillator** [comment]
same thing seems to happen if the default port 65565 is occupied on first run.

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryMod/commit/a79404df33a57208ceb02f66a861be7abe593ed4#diff-b45099b418853cbce0698ea6846944b3R19
