### ISSUE TITLE
NullPointerException in PlayerManager

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#175]
Server threw this exception when I teleported to a world with a command and then shut itself down because `A single server tick took 60.00 seconds (should be max 0.05)`. I'm not sure what conditions caused the crash, will try to reproduce.

```
[23:28:19] [net.minecraft.server.MinecraftServer] [ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:670) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:436) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:583) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488) [CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerManager.b(PlayerManager.java:68) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.WorldServer.c(WorldServer.java:195) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:665) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	... 4 more
```

**Comment by gerardvanschip** [comment]
Build 183 has been replaced by the release 663 build which includes fixes.
https://ci.visualillusionsent.net/job/CanaryMod/

**Comment by toddharrison** [comment]
Looks like this is resolved in build 680. Thanks!
