### ISSUE TITLE
NullPointerException thrown by PlayerManager

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#179]
I am getting an occasional NullPointerException from the PlayerManager. This seems to happen when one player dies in my island world and respawns, but only when another player is in the same island world at the same time. The server tries to delete all the blocks associated with their island. At the same time it clears some XML data for the player. This work happens on a separate java Thread as well. I will do some experimentation and see if I can nail down the error at all.

```
[11:10:34] [net.minecraft.server.MinecraftServer] [ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:674) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:587) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489) [CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerManager.b(PlayerManager.java:68) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.WorldServer.c(WorldServer.java:195) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:669) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	... 4 more

**Comment by darkdiplomat** [comment]
this matches https://github.com/CanaryModTeam/CanaryMod/issues/175
