### ISSUE TITLE
Issues with GroupMod

### ISSUE THREAD

**Issue by clucky** [CanaryModTeam/CanaryMod#190]
I have encountered several bugs with groupmod:

**Bug 1** (Although there is an error, the players are successfully renamed to testers)
Stacktrace upon renaming a group
````
> groupmod rename players testers
> [02:42:03] [CanaryMod] [ERROR]: Could not execute command...
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819) ~[?:1.7.0_07]
        at java.util.ArrayList$Itr.next(ArrayList.java:791) ~[?:1.7.0_07]
        at net.canarymod.user.UserAndGroupsProvider.renameGroup(UserAndGroupsProvider.java:123) ~[CanaryMod-1.8.0-1.2.0-
SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.commands.groupmod.GroupRename.execute(GroupRename.java:26) ~[CanaryMod-1.8.0-1.2.0-S
NAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.CommandList.groupRename(CommandList.java:636) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shade
d.jar:1.8.0-1.2.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_07]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_07]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_07]
        at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0_07]
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:322) [CanaryMod-1.8.0-1.2.0-SNAPSHOT-sh
aded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:103) [CanaryMod-1.8.0-1.2.0-SNAPSHOT-s
haded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:201) [CanaryMod-1.8.0-1.2.0-SNAPSHOT
-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.CanaryServer.consoleCommand(CanaryServer.java:172) [CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.j
ar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:140) [CanaryMod-1.8.0-1.2.0-SNAPSHO
T-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
````

**bug 2** (unknown cause, chat sourced from IRC, edited for relevance)
Huge console spam and failure to load after restart

>[02:31] <x_clucky> darkdiplomat, the commands in-game do not match up with the commands in the handbook for groupmod
>[02:33] <x_clucky> i managed to crash groupmod somehow.
>[02:38] <x_clucky> http://pastebin.com/yNUN5du0
>[02:41] <x_clucky> and a crash report when I restarted the server: http://pastebin.com/N1QfWtve

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryLib/commit/e94ce63da739984bed32e9480861870f16b7e9af
Should correct the null pointer in whitelist command, the other issue has already been migrated to the correct repository
