### ISSUE TITLE
Snapshot #699 java.lang.NullPointer crashes 

### ISSUE THREAD

**Issue by Nutmegan** [CanaryModTeam/CanaryMod#193]
I'm trying to create a new multi-world test server but having numerous crashes with this same NullPointer (below).

Unfortunately I can't isolate a more specific issue giving the error. Here are some of the actions I was doing just before the log registered the error. These errors are spread across 3 different server instances I tried creating. (I tossed out the old ones after too many errors and started over). These were clean copies with no installed plugins.

3 times - Player kicked for idleing
2 times - Changing gamemodes (might be unrelated, more likely related to spawning into a new world that was still rendering)
2 times - Player lost connection (server overload? While building a new world at about 96%)
2 times - While Loading a World (for the first time.)
1 time - While loading a new region (to an imported world)
1 time - On server start up before players were in the world
1 time - as soon as started moving in newly spawned world

[code][10:16:55] [net.minecraft.server.MinecraftServer] [ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world entities
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:683) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:587) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489) [CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.EntityTracker.b(EntityTracker.java:195) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.WorldManager.b(WorldManager.java:35) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.World.b(World.java:887) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.WorldServer.b(WorldServer.java:824) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.World.i(World.java:1172) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.world.WorldServer.i(WorldServer.java:480) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:678) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	... 4 more[/code]

**Comment by Nutmegan** [comment]
Ok, I'm not the most tech savvy person, but here's my very simplified assessment. It's definitely related to CanaryMod Gui. I assume it isn't allocating enough memory as the errors all seem to be happening after "system falling behind skipping ticks" messages.

Starting from my own .bat I get few falling behind messages and seem to recover faster. I also seem to be getting no fatal crashes.

So I guess maybe this isn't a real bug, perhaps an issue to note. It doesn't seem to me the gui can support a running server the way it's configured at the moment or maybe my system in conjunction with the gui is the issue. Anyway, do what you want with it.

**Comment by sennewood** [comment]
How many worlds are loaded when the server crashed? I tested up to 5 worlds and have no problems.

**Comment by Nutmegan** [comment]
Only one for some of them, but 2 for most. It could have something to do dedicated memory. I'm running my server tests on my little MacBook. Anyway, it works fine when I dedicate memory from a .bat command so I'll just not run it from the GUI.
