### ISSUE TITLE
sethome command error

### ISSUE THREAD

**Issue by tylerhoot** [CanaryModTeam/CanaryMod#200]
[22:46:32] [CanaryMod] [ERROR]: Could not execute command...
java.lang.ArrayIndexOutOfBoundsException: 1
        at net.canarymod.commandsys.commands.warp.SetHome.player(SetHome.java:41
) ~[CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.commands.warp.SetHome.execute(SetHome.java:2
3) ~[CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.CommandList.setHomeCommand(CommandList.java:
1745) ~[CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java
:322) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.jav
a:103) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.j
ava:189) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.executeCommand(
CanaryPlayer.java:372) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.chat(CanaryPlay
er.java:186) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.jav
a:841) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.network.play.client.C01PacketChatMessage.a(C01PacketCha
tMessage.java:34) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.network.play.client.C01PacketChatMessage.a(C01PacketCha
tMessage.java:42) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:17
) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]

        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:638) [Can
aryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java
:446) [CanaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:587) [Can
aryMod.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489) [C
anaryMod.jar:1.8.0-1.2.0-SNAPSHOT]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by tylerhoot** [comment]
[22:46:32] [CanaryMod] [INFO]: Command used by RyneWilson: /sethome 2
missed a peace of the error
