### ISSUE TITLE
Spawn ConcurrentModificationException

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#205]
I get the following concurrent mod exception occasionally when I do a `/spawn foo` which crashes the server:

    [20:31:12] [net.minecraft.server.MinecraftServer] [ERROR]: Encountered an unexpected exception net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:683) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:587) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
    Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_20]
	at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_20]
	at net.minecraft.entity.player.EntityPlayerMP.s_(EntityPlayerMP.java:299) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.world.World.a(World.java:1329) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.world.WorldServer.a(WorldServer.java:613) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.world.World.g(World.java:1309) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.world.World.i(World.java:1188) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.world.WorldServer.i(WorldServer.java:480) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:678) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	... 4 more

**Comment by darkdiplomat** [comment]
Hopefully the added synchronization helps prevent further issues.

**Comment by darkdiplomat** [comment]
Before I close this out, just want to double check if the issues is still happening or seems to have been corrected.

**Comment by toddharrison** [comment]
I have not gotten the error recently, I think it's been fixed.
