### ISSUE TITLE
Error causing players to appear offline (and invisible), yet are technically still online.

### ISSUE THREAD

**Issue by clucky** [CanaryModTeam/CanaryMod#214]
An error I have stumbled upon with one of the more recent nightly builds (Version numbers are not included on /version). It causes the server to spam login/logout messages, the last of which being a logout; however, the player is not logged out and can still break blocks, move, and attack (probably interact completely with the server). They are, however, invisible to other players.

````
[21:38:27] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@5e7348d6 to net.minecraft.server.network.NetHandlerHandshakeTCP@5a4cc7c0
[21:38:27] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:27] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:27] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@5e7348d6 to net.minecraft.server.network.NetHandlerLoginServer@1f4e42ed
[21:38:29] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Opening connection to https://sessionserver.mojang.com/session/minecraft/hasJoined?serverId=-184af96a0aff4022fc995072ad25828a8b55fe0c&username=NG_Lucius
[21:38:29] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Reading data from https://sessionserver.mojang.com/session/minecraft/hasJoined?serverId=-184af96a0aff4022fc995072ad25828a8b55fe0c&username=NG_Lucius
[21:38:29] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Successful read, server response was 200
[21:38:29] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Response: {"id":"0491a468ee2b4e8bb3a393b25c93ecfd","name":"NG_Lucius","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0Mjg3MTYzMTY3MTAsInByb2ZpbGVJZCI6IjA0OTFhNDY4ZWUyYjRlOGJiM2EzOTNiMjVjOTNlY2ZkIiwicHJvZmlsZU5hbWUiOiJOR19MdWNpdXMiLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y3ZTBiZDJlODk3MjdjMWJhZjJmYTM2NTY5MTQ3MTU4YjVjZDZiMmM1NGM3NDJmNjdkNzllYzk0Mzk1MDI4In19fQ==","signature":"A0lL0c/D04JQw2x442YTDfGOYZrha8jY4sm+KiXf1QEH7bJB+IdPgtXsaAJKcpYL13z92inZq+h/68sqZ3Dj1Gl3OyAfrLuo76z3qTQrKAJ7ZCDwHBmG1VQZCFB0AyNc8hE/VRfzaF9R/U4hc+scBH0UXfkKaMK1jPPEzjoGuI4AFQ1PG8LgjLHDVDmjJzennMa4RPIEeUuHkhUZNIaPwnS8GzrgWGqa/+41UQj7cOjcIQ+/Vw+0nbMnZf5mTjuEFbQEmbZQ8NC/3YE3SkfLBgYbtukTEPgJw1mff6xNnkKlcrFESt1m56NsCmkjf6mSrgJKOsGg2JyamWz6rf6aVLmZquo41gVYtEtNhiM1FChA0wimzEKS/MY3RS3RMdo7oBphAEau84SKG9acJYE3XbqwreyGfr62McUUojFCP5WK4AWSeTtBWwlWbmBdJ/cqLUGt1raA/oABGl0oWyiSgIBgrnEruUa+DG/9/2FvBzjPZr1MnGV2fhhmlQnFgkY0qBx5KoqWhwrs4soIIMBIFxqbCjCSDzTxW9T+6sOdRKwXaWG3y4dX81sAILR/D1rjRD6MmT2KNYN5zHSdJhhwjju/jJLSnjrFU07V2INiSJh+LhjZFmJBUWlMyKJEM/PdrbmaviJ6Q2Oro+TIqNOlQ6sRjqPjd1JRbnEJEB4qadQ="}]}
[21:38:29] [net.minecraft.server.network.NetHandlerLoginServer] [INFO]: UUID of player NG_Lucius is 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd
[21:38:29] [net.minecraft.server.management.ServerConfigurationManager] [INFO]: NG_Lucius[/75.83.191.75:49062] logged in with entity id 23772 at (74.76814854368041, 11.0, 43.71042995658351)
[21:38:29] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@5e7348d6 to net.minecraft.network.NetHandlerPlayServer@440a2251
[21:38:29] [net.minecraft.network.NetworkManager] [DEBUG]: Disabled auto read
[21:38:29] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:29] [CCSkills] [DEBUG]: PlayerSkillData object for 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd successfully loaded.
[21:38:29] [net.minecraft.server.MinecraftServer] [INFO]: NG_Lucius joined the game
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@60f6e08b to net.minecraft.server.network.NetHandlerHandshakeTCP@64c9784d
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@60f6e08b to net.minecraft.server.network.NetHandlerLoginServer@21cbeab0
[21:38:30] [net.minecraft.network.NetHandlerPlayServer] [ERROR]: Error receiving 'C17PacketCustomPayload': readerIndex(1) + length(70) exceeds writerIndex(47): SlicedByteBuf(ridx: 1, widx: 47, cap: 47/47, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 47, cap: 47))
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(70) exceeds writerIndex(47): SlicedByteBuf(ridx: 1, widx: 47, cap: 47/47, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 47, cap: 47))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:648) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:561) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.c(PacketBuffer.java:214) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.java:1377) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:34) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:46) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:17) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:640) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[21:38:30] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Opening connection to https://sessionserver.mojang.com/session/minecraft/hasJoined?serverId=74d50aff9791ee76b358c9b190dca56885f29110&username=NG_Lucius
[21:38:30] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Reading data from https://sessionserver.mojang.com/session/minecraft/hasJoined?serverId=74d50aff9791ee76b358c9b190dca56885f29110&username=NG_Lucius
[21:38:30] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Successful read, server response was 200
[21:38:30] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Response: {"id":"0491a468ee2b4e8bb3a393b25c93ecfd","name":"NG_Lucius","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0Mjg3MTYzMTc4MDUsInByb2ZpbGVJZCI6IjA0OTFhNDY4ZWUyYjRlOGJiM2EzOTNiMjVjOTNlY2ZkIiwicHJvZmlsZU5hbWUiOiJOR19MdWNpdXMiLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y3ZTBiZDJlODk3MjdjMWJhZjJmYTM2NTY5MTQ3MTU4YjVjZDZiMmM1NGM3NDJmNjdkNzllYzk0Mzk1MDI4In19fQ==","signature":"gTd+0aMuBbgLDCoKPeBNF0uYxhjgJULiyplPlR8RivNJfUhCAlXJVplrygNzPGPxuOCmjqCIm0NDCqNjqyzsgwvDHby8V3jaqA437VfmNZ25KTCwK68E1nAFytiFa5R5YxGjRZe7agSLg4ZhLGfxtKW3ZokF7Igitrz7cwM12Hh8ZTkxKuW7itdQ18sEH5sWPiEYh914HkkRhop492+kv8+2w6yNT8hLRarJ/WFeNIWIEP9M6MVLapRXtKraxMiALa3Rx5jVr4EqvCjaZy2WS//0k8BDovXhnO3RxVjRguXAKJmwVo6jzozVE8X0UQLeme332WlFOtiY3OaVxaX2l5sYZujiFvS85stI4+jAnXNas0L7H22XNq0lol+nqnCEHheAlrvptE0155Ene+bYY3T3yS1ADuziDpyyh7HQ06N6W1CT7kuYLn3mgmzFSsAxZ0/itE3eD6ipj8ICMGxmE8DYwYuonbgSP6wJWZnoGFCVI3hXSY9zcMmpL2MgBTemQduX1bWr6LcgX5fhPOHKVvk3kgRLDFd4H8iP0TSg7ERiVH9ZXs2OrMGLWx+M/GQBpvLC+5E28BoD3ZWM1I2SRH/IXRoudz+7yDuAbJzh42WX1dhogkk+dbfBD/yPXGXNNzhGsS2YNZsWU20dlkv46ycMZWfwJ4OkJ21Z4m1roP8="}]}
[21:38:30] [net.minecraft.server.network.NetHandlerLoginServer] [INFO]: UUID of player NG_Lucius is 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd
[21:38:30] [net.minecraft.server.management.ServerConfigurationManager] [INFO]: NG_Lucius[/75.83.191.75:37300] logged in with entity id 27334 at (74.76814854368041, 11.0, 43.71042995658351)
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@60f6e08b to net.minecraft.network.NetHandlerPlayServer@56441e99
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Disabled auto read
[21:38:30] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:30] [CCSkills] [DEBUG]: PlayerSkillData object for 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd successfully loaded.
[21:38:30] [net.minecraft.server.MinecraftServer] [INFO]: NG_Lucius joined the game
[21:38:30] [net.minecraft.network.NetHandlerPlayServer] [INFO]: NG_Lucius lost connection: You logged in from another location
[21:38:30] [CCSkills] [DEBUG]: Saved PlayerSkillData object for 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd successfully.
[21:38:30] [net.minecraft.server.MinecraftServer] [INFO]: NG_Lucius left the game
[21:38:31] [net.minecraft.network.NetHandlerPlayServer] [ERROR]: Error receiving 'C17PacketCustomPayload': readerIndex(1) + length(70) exceeds writerIndex(47): SlicedByteBuf(ridx: 1, widx: 47, cap: 47/47, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 47, cap: 47))
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(70) exceeds writerIndex(47): SlicedByteBuf(ridx: 1, widx: 47, cap: 47/47, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 47, cap: 47))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:648) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:561) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.c(PacketBuffer.java:214) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.java:1377) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:34) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:46) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:17) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:640) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[21:38:32] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@3942d3e2 to net.minecraft.server.network.NetHandlerHandshakeTCP@3d7d4012
[21:38:32] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:32] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:32] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@3942d3e2 to net.minecraft.server.network.NetHandlerLoginServer@787fd9d9
[21:38:33] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Opening connection to https://sessionserver.mojang.com/session/minecraft/hasJoined?serverId=-4a75792bc178f7a4e4115b915729dc3a3d90e05f&username=NG_Lucius
[21:38:33] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Reading data from https://sessionserver.mojang.com/session/minecraft/hasJoined?serverId=-4a75792bc178f7a4e4115b915729dc3a3d90e05f&username=NG_Lucius
[21:38:33] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Successful read, server response was 200
[21:38:33] [com.mojang.authlib.HttpAuthenticationService] [DEBUG]: Response: {"id":"0491a468ee2b4e8bb3a393b25c93ecfd","name":"NG_Lucius","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0Mjg3MTYzMjA2ODYsInByb2ZpbGVJZCI6IjA0OTFhNDY4ZWUyYjRlOGJiM2EzOTNiMjVjOTNlY2ZkIiwicHJvZmlsZU5hbWUiOiJOR19MdWNpdXMiLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y3ZTBiZDJlODk3MjdjMWJhZjJmYTM2NTY5MTQ3MTU4YjVjZDZiMmM1NGM3NDJmNjdkNzllYzk0Mzk1MDI4In19fQ==","signature":"Vo8NuNetKyryGj3USqO4oINCl/Pi9lKWd7qxSlEV+7MKI0wM+Q4mMSwnfpWkdwUhSBo/O9HjYTxJIh6T7vYWab5wV23bXHtBh2hn9Mprk4+f4T+ApEqOKSDvKrNwKzlyhIBBsozohpc/BUSOh7Yd0ZzFHD3N1PATT2rFLX1Qk3Z7PyNfbVho/V484d+UblyD2Wa7fQip3eFEUSBrKefcsvevPZWNteRFVVJyLWYgB1fZOB5GzfiS3EHzSB3ernlsO8831KFMg9vIRbbG7HeDuMU0MTHSKgmyQv94lThKaZYPXmfjq0qOaIZfu3BKawm6WTpZQFJhDeaBsyVryO6kZqpRnJppdt7mRkSGG2MzDRG84SxrdqU2Pd/6Gy9yZkWLD8YI0tfqXXiE+tFA5hlqruDeZnZGrCKBPC1FH+RPLjUvr0jM7uPsfR2MMV9tUzBE/GiAMYmOIXcMUpQ9VNhLT6hhich+nkfKUDQi9mD1163YrhGZMOiqwzWIQOEv7T9ZM3PJEbU5AIfw5RZ9ConRxIRK52/Opm7++D5mqC+IYzu5V6YJn18wBXvXS9BmGQLG8GMMfEY71cjSvrZR/HfCZO8qxZaaxejkcn/IEPd6g8j/0wuja93stBbwWsljaYSjVSeavTSC0Vo4U47W3TR8ll0SSubcUnXADtlsIqv9LAE="}]}
[21:38:33] [net.minecraft.server.network.NetHandlerLoginServer] [INFO]: UUID of player NG_Lucius is 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd
[21:38:33] [net.minecraft.server.management.ServerConfigurationManager] [INFO]: NG_Lucius[/75.83.191.75:43065] logged in with entity id 35261 at (74.76814854368041, 11.0, 43.71042995658351)
[21:38:33] [net.minecraft.network.NetworkManager] [DEBUG]: Set listener of net.minecraft.network.NetworkManager@3942d3e2 to net.minecraft.network.NetHandlerPlayServer@711bbf00
[21:38:33] [net.minecraft.network.NetworkManager] [DEBUG]: Disabled auto read
[21:38:33] [net.minecraft.network.NetworkManager] [DEBUG]: Enabled auto read
[21:38:33] [CCSkills] [DEBUG]: PlayerSkillData object for 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd successfully loaded.
[21:38:33] [net.minecraft.server.MinecraftServer] [INFO]: NG_Lucius joined the game
[21:38:33] [net.minecraft.network.NetHandlerPlayServer] [INFO]: NG_Lucius lost connection: You logged in from another location
[21:38:33] [CCSkills] [DEBUG]: Saved PlayerSkillData object for 0491a468-ee2b-4e8b-b3a3-93b25c93ecfd successfully.
[21:38:33] [net.minecraft.server.MinecraftServer] [INFO]: NG_Lucius left the game
[21:38:33] [net.minecraft.network.NetHandlerPlayServer] [ERROR]: Error receiving 'C17PacketCustomPayload': readerIndex(1) + length(70) exceeds writerIndex(47): SlicedByteBuf(ridx: 1, widx: 47, cap: 47/47, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 47, cap: 47))
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(70) exceeds writerIndex(47): SlicedByteBuf(ridx: 1, widx: 47, cap: 47/47, unwrapped: UnpooledHeapByteBuf(ridx: 0, widx: 47, cap: 47))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:648) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:561) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.c(PacketBuffer.java:214) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.java:1377) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:34) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:46) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:17) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:640) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[21:38:36] [net.minecraft.network.NetHandlerPlayServer] [ERROR]: Error receiving 'C17PacketCustomPayload': readerIndex(1) + length(5) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(5) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:669) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:677) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:581) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketBuffer.a(PacketBuffer.java:59) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.java:1400) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:34) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.play.client.C17PacketCustomPayload.a(C17PacketCustomPayload.java:46) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:17) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:640) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
````

**Comment by darkdiplomat** [comment]
This looks like clients sending bad custom packets.

**Comment by clucky** [comment]
This has been confirmed to be fixed in the above commit.
