### ISSUE TITLE
water

### ISSUE THREAD

**Issue by tylerhoot** [CanaryModTeam/CanaryMod#215]
at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:129) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.Hook.call(Hook.java:37) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.CancelableHook.call(CancelableHook.java:26) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.h(BlockDynamicLiquid.java:267) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.b(BlockDynamicLiquid.java:112) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.a(WorldServer.java:532) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.c(WorldServer.java:191) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:671) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Comment by darkdiplomat** [comment]
I am gonna need more detail here. As far as I can tell, the hook is working fine without throwing errors

**Comment by tylerhoot** [comment]
16:00:09] [CanaryMod] [ERROR]: Exception while executing Hook: LiquidDestroyHook in PluginListener: OurLiquidDestroyTrigger (Plugin: dynmap)
java.lang.NoSuchMethodError: net.canarymod.api.world.blocks.Block.getData()S
        at org.dynmap.canary.DynmapPlugin.checkBlock(DynmapPlugin.java:1107) ~[?:?]
        at org.dynmap.canary.DynmapPlugin.access$2300(DynmapPlugin.java:98) ~[?:?]
        at org.dynmap.canary.DynmapPlugin$OurLiquidDestroyTrigger.onLiquidDestroy(DynmapPlugin.java:1464) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:59) ~[CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.plugin.RegisteredPluginListener.execute(RegisteredPluginListener.java:52) ~[CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:129) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.Hook.call(Hook.java:37) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.CancelableHook.call(CancelableHook.java:26) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.h(BlockDynamicLiquid.java:267) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.b(BlockDynamicLiquid.java:112) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.a(WorldServer.java:532) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.c(WorldServer.java:191) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:671) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by tylerhoot** [comment]
that is the full error

**Comment by darkdiplomat** [comment]
It's a split between CanaryMod and Dynamap actually. Dynamap is compiled against an older version of CanaryMod when Block.getData returned a short. Block.getData now returns a Integer. Recompiling should be enough to correct that issue 


(or modifiying the byte code directly in the current jar to make it an I rather than an S)

**Comment by tylerhoot** [comment]
can I put a copy of your message in his bug tracker on git hub or do you want to do it? i have that bug reported on his git hub issue tracker
