### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tylerhoot** [CanaryModTeam/CanaryMod#219]
ava:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:59)
        at net.canarymod.plugin.RegisteredPluginListener.execute(RegisteredPluginListener.java:52)
        at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:129)
        at net.canarymod.hook.Hook.call(Hook.java:37)
        at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:204)
        at net.minecraft.server.network.NetHandlerLoginServer.b(NetHandlerLoginServer.java:102)
        at net.minecraft.server.network.NetHandlerLoginServer.c(NetHandlerLoginServer.java:59)
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:186)
        at net.minecraft.network.NetworkSystem.c(NetworkSystem.java:140)
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:698)
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446)
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491)
        at java.lang.Thread.run(Thread.java:745)

**Comment by 14mRh4X0r** [comment]
What are we even supposed to with a bug report like this?
