### ISSUE TITLE
exception using /kit give command

### ISSUE THREAD

**Issue by Nutmegan** [CanaryModTeam/CanaryMod#230]
Player issued command /kit give <kit name>  (no player specified)  is throwing the following exception error:

java.lang.ArrayIndexOutOfBoundsException: 1
	at net.canarymod.commandsys.commands.system.kits.KitGive.asPlayer(KitGive.java:52) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.canarymod.commandsys.commands.system.kits.KitGive.execute(KitGive.java:28) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.canarymod.commandsys.CommandList.kitGiveCommand(CommandList.java:1067) ~[CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:322) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:103) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:201) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.canarymod.api.entity.living.humanoid.CanaryPlayer.executeCommand(CanaryPlayer.java:381) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.canarymod.api.entity.living.humanoid.CanaryPlayer.chat(CanaryPlayer.java:194) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.java:850) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.network.play.client.C01PacketChatMessage.a(C01PacketChatMessage.java:34) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.network.play.client.C01PacketChatMessage.a(C01PacketChatMessage.java:42) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:17) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:640) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar:1.8.0-1.2.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[16:05:05] [CanaryMod] [INFO]: Command used by Nutmegan: /kit give newtest

**Comment by Larry1123** [comment]
This is a CanaryLib issue and I think I have a working fix, I will reopen this issue in the right place and link a jar with the change, once you test it let me know and I will push the fix it.

**Comment by Nutmegan** [comment]
The exception is indeed gone. However, the game chat console is still printing up the following message in red (error) text formatting:
"This kit is currently unavailable"
"SomeKitName is not a Kit"

This is after it actually gives the player the items in the kit that they requested. Not a huge issue, just not correct.

Is there an easy way to know when bugs should be in the Lib vs the Mod? I don't really deal in the code, so is there another way?

**Comment by Larry1123** [comment]
All the commands added in canary are going to be lib stuff.
I'll look into that other part, from what I saw in the code that error should have only happen if their is no kit by that name.

**Comment by Nutmegan** [comment]
Arg... your fix broke one of my hacks. lol

I was using a delay of 0 to only allow the player to receive the kit one time ever. Now they can call it as much as they like. Is there another way to limit how many times they receive a kit? If not, I have another trick I can try with another plugin.

**Comment by Larry1123** [comment]
I did not change anything to do with the kits, I only fixed what was causing that stacktrace in the command.

I don't know what could be wrong with how that works...

**Comment by Nutmegan** [comment]
Ok, It was probably just a bad test on my part. I'll just set it at a year.
Do you need me to open a different issue report for the chat display issues and close this one? The kit has to be valid because the requester still gets the kit, it just says they can't get it.

**Comment by Larry1123** [comment]
I don't see how that can happen from the code side as it could only return that result if the function to apply the kit is never ran... can you confirm this for me.
http://git.io/vLnpm with http://git.io/vLnpR

**Comment by Nutmegan** [comment]
This set of events is exactly what I'm seeing... each case is being printed on the screen.
I'm not a coder, but shouldn't there be brakes after all these cases?

    protected void asPlayer(Player player, String[] args) {
        // Give kit to player
        if (args.length == 1) {
            Result result = doGive(player, kits.getKit(args[0]), false);
            switch (result) {
                case GIVEN:
                    sendTranslatedMessage(player, ChatFormat.YELLOW, "kit given");
                case UNAVAILABLE:
                    sendTranslatedNotice(player, "kit unavailable");
                case INVALID:
                    sendTranslatedNotice(player, "kit invalid", args[1]);
            }
        }

**Comment by Larry1123** [comment]
Oh wow, who in the world made this there are no brakes!

**Comment by Nutmegan** [comment]
It looks great. Thanks for the help.
