### ISSUE TITLE
Game client crashes when trying to download texture pack

### ISSUE THREAD

**Issue by walterhiggins** [CanaryModTeam/CanaryMod#231]
I've set the texture-pack option in config/server.cfg as follows:

    texture-pack=http://scriptcraftjs.org/download/CustomSounds.zip

When I start canarymod and then try to connect from the client, I get the texture-pack prompt screen:

During startup the client crashes. There's nothing in the server console that indicates anything happened on the server. This resource file mentioned above is the same resource file used here http://mentalblockgaming.com/blog/sound/importing-custom-sounds-into-minecraft/

The client error is pasted below this line

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 21/06/15 10:55
Description: Updating screen events

java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
	at bnm.i(SourceFile:218)
	at bnm.a(SourceFile:184)
	at bcy$3$1.a(SourceFile:1233)
	at awy.a(SourceFile:50)
	at axu.a(SourceFile:350)
	at axu.k(SourceFile:413)
	at axu.p(SourceFile:390)
	at ave.s(SourceFile:1497)
	at ave.av(SourceFile:888)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:545)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:521)
	at bnm.i(SourceFile:218)
	at bnm.a(SourceFile:184)
	at bcy$3$1.a(SourceFile:1233)
	at awy.a(SourceFile:50)
	at axu.a(SourceFile:350)
	at axu.k(SourceFile:413)
	at axu.p(SourceFile:390)

-- Affected screen --
Details:
	Screen name: awy

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bew['walterh'/19, l='MpServer', x=181.50, y=74.00, z=15.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 184.00,64.00,20.00 - World: (184,64,20), Chunk: (at 8,4,4 in 11,1; contains blocks 176,0,16 to 191,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 23421 game time, 23421 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 111 total; [bew['walterh'/19, l='MpServer', x=181.50, y=74.00, z=15.50], tx['Squid'/256, l='MpServer', x=219.75, y=58.79, z=-37.69], tx['Squid'/257, l='MpServer', x=216.88, y=57.13, z=-34.24], vt['Guardian'/1281, l='MpServer', x=117.50, y=51.28, z=94.50], tx['Squid'/258, l='MpServer', x=224.80, y=57.76, z=-35.81], tx['Squid'/259, l='MpServer', x=220.00, y=56.66, z=-33.79], vt['Guardian'/1539, l='MpServer', x=113.50, y=52.81, z=84.50], vt['Guardian'/6, l='MpServer', x=103.53, y=52.00, z=75.97], vt['Guardian'/1542, l='MpServer', x=108.62, y=57.35, z=73.42], tx['Squid'/775, l='MpServer', x=147.78, y=48.09, z=71.73], vt['Guardian'/7, l='MpServer', x=117.00, y=42.00, z=80.56], uz['item.tile.mushroom'/8, l='MpServer', x=153.16, y=11.00, z=51.88], tx['Squid'/776, l='MpServer', x=140.28, y=49.79, z=76.38], tx['Squid'/777, l='MpServer', x=140.80, y=49.99, z=70.75], tx['Squid'/778, l='MpServer', x=150.72, y=48.88, z=79.81], tk['Bat'/1550, l='MpServer', x=127.11, y=15.66, z=3.56], tx['Squid'/787, l='MpServer', x=144.34, y=49.34, z=64.96], tx['Squid'/788, l='MpServer', x=149.75, y=46.85, z=60.06], tx['Squid'/789, l='MpServer', x=144.19, y=46.20, z=71.43], tx['Squid'/791, l='MpServer', x=136.47, y=47.53, z=58.50], tk['Bat'/1561, l='MpServer', x=178.49, y=24.24, z=12.99], vt['Guardian'/1050, l='MpServer', x=132.50, y=46.59, z=90.50], tx['Squid'/284, l='MpServer', x=225.05, y=52.67, z=2.96], tx['Squid'/285, l='MpServer', x=224.11, y=50.53, z=4.43], tx['Squid'/286, l='MpServer', x=221.44, y=48.80, z=3.10], tx['Squid'/287, l='MpServer', x=227.70, y=51.60, z=-4.93], vt['Guardian'/31, l='MpServer', x=102.31, y=58.61, z=64.69], vt['Guardian'/35, l='MpServer', x=114.50, y=56.63, z=51.50], tk['Bat'/1575, l='MpServer', x=214.87, y=14.04, z=-3.33], vt['Guardian'/45, l='MpServer', x=105.50, y=39.91, z=58.50], tx['Squid'/558, l='MpServer', x=158.31, y=60.69, z=49.41], vt['Guardian'/46, l='MpServer', x=106.50, y=39.91, z=53.50], tx['Squid'/559, l='MpServer', x=157.82, y=59.85, z=53.80], vt['Guardian'/47, l='MpServer', x=98.41, y=44.00, z=57.41], tx['Squid'/560, l='MpServer', x=155.35, y=60.01, z=52.32], vt['Guardian'/48, l='MpServer', x=105.50, y=39.91, z=60.50], tx['Squid'/561, l='MpServer', x=164.41, y=61.13, z=52.70], tx['Squid'/562, l='MpServer', x=179.84, y=47.07, z=-16.88], tx['Squid'/563, l='MpServer', x=181.35, y=47.89, z=-20.11], tx['Squid'/564, l='MpServer', x=182.43, y=48.81, z=-14.75], tx['Squid'/565, l='MpServer', x=180.21, y=49.32, z=-11.22], tk['Bat'/57, l='MpServer', x=159.95, y=34.02, z=-3.45], vt['Guardian'/1341, l='MpServer', x=104.73, y=45.64, z=94.37], vt['Guardian'/1344, l='MpServer', x=123.50, y=56.88, z=46.50], tk['Bat'/1601, l='MpServer', x=145.99, y=28.66, z=-8.49], tk['Bat'/1602, l='MpServer', x=259.38, y=12.39, z=19.90], tx['Squid'/581, l='MpServer', x=148.80, y=46.63, z=-45.80], tx['Squid'/582, l='MpServer', x=158.47, y=62.44, z=57.32], tx['Squid'/583, l='MpServer', x=158.39, y=61.24, z=54.85], tx['Squid'/584, l='MpServer', x=167.42, y=60.22, z=60.13], tx['Squid'/585, l='MpServer', x=155.39, y=61.34, z=50.59], tx['Squid'/332, l='MpServer', x=145.74, y=58.00, z=29.77], tx['Squid'/333, l='MpServer', x=141.07, y=56.59, z=27.96], tx['Squid'/335, l='MpServer', x=145.84, y=58.22, z=21.70], tx['Squid'/336, l='MpServer', x=137.33, y=58.41, z=25.34], vn['Creeper'/1361, l='MpServer', x=104.50, y=25.00, z=41.50], tx['Squid'/82, l='MpServer', x=219.25, y=46.47, z=17.36], tx['Squid'/83, l='MpServer', x=221.37, y=49.04, z=24.31], vn['Creeper'/1363, l='MpServer', x=103.50, y=25.00, z=43.50], tx['Squid'/84, l='MpServer', x=228.44, y=47.54, z=27.76], tx['Squid'/85, l='MpServer', x=224.94, y=44.65, z=36.46], vt['Guardian'/1365, l='MpServer', x=119.56, y=41.00, z=87.03], vt['Guardian'/1366, l='MpServer', x=121.50, y=40.91, z=83.50], vt['Guardian'/855, l='MpServer', x=129.82, y=62.28, z=53.24], vt['Guardian'/1118, l='MpServer', x=110.50, y=39.91, z=59.50], vt['Guardian'/1121, l='MpServer', x=114.41, y=39.91, z=59.50], vt['Guardian'/1122, l='MpServer', x=115.97, y=39.91, z=59.50], vt['Guardian'/1123, l='MpServer', x=118.03, y=39.91, z=59.50], vt['Guardian'/1127, l='MpServer', x=107.50, y=51.28, z=93.50], vt['Guardian'/1143, l='MpServer', x=118.50, y=49.72, z=89.50], vt['Guardian'/1399, l='MpServer', x=132.50, y=48.13, z=95.50], vt['Guardian'/1415, l='MpServer', x=103.50, y=57.13, z=43.50], tk['Bat'/906, l='MpServer', x=198.82, y=24.17, z=-11.95], vt['Guardian'/1419, l='MpServer', x=131.50, y=52.44, z=59.50], vt['Guardian'/1167, l='MpServer', x=116.50, y=50.88, z=56.50], tx['Squid'/659, l='MpServer', x=125.48, y=62.35, z=-40.56], tx['Squid'/660, l='MpServer', x=121.37, y=62.12, z=-43.14], tx['Squid'/661, l='MpServer', x=129.57, y=61.70, z=-36.72], tx['Squid'/662, l='MpServer', x=126.80, y=61.18, z=-39.56], vt['Guardian'/1174, l='MpServer', x=118.44, y=46.56, z=93.22], vt['Guardian'/923, l='MpServer', x=113.50, y=40.88, z=48.50], vt['Guardian'/927, l='MpServer', x=119.50, y=43.91, z=51.50], vt['Guardian'/928, l='MpServer', x=121.50, y=43.91, z=50.50], wc['Spider'/941, l='MpServer', x=147.28, y=30.00, z=10.94], wa['Skeleton'/943, l='MpServer', x=149.50, y=31.00, z=8.50], tx['Squid'/178, l='MpServer', x=212.51, y=57.03, z=-48.24], tx['Squid'/179, l='MpServer', x=210.31, y=54.65, z=-42.67], tx['Squid'/182, l='MpServer', x=228.33, y=45.48, z=-7.59], tx['Squid'/183, l='MpServer', x=225.99, y=46.06, z=-3.32], tx['Squid'/184, l='MpServer', x=220.67, y=48.74, z=-6.59], we['Zombie'/1464, l='MpServer', x=125.50, y=22.00, z=-40.50], tx['Squid'/185, l='MpServer', x=217.07, y=46.22, z=-12.82], vt['Guardian'/1467, l='MpServer', x=121.90, y=62.83, z=89.29], vt['Guardian'/1469, l='MpServer', x=122.85, y=59.10, z=87.59], vt['Guardian'/1215, l='MpServer', x=118.66, y=48.59, z=51.28], vt['Guardian'/962, l='MpServer', x=130.37, y=45.94, z=87.50], vt['Guardian'/963, l='MpServer', x=123.41, y=47.00, z=84.96], tx['Squid'/461, l='MpServer', x=189.12, y=47.80, z=-46.08], tx['Squid'/462, l='MpServer', x=175.85, y=51.17, z=-14.03], tx['Squid'/463, l='MpServer', x=187.53, y=52.13, z=-10.47], tx['Squid'/464, l='MpServer', x=171.93, y=51.13, z=-12.27], tk['Bat'/1488, l='MpServer', x=154.65, y=34.10, z=15.44], tx['Squid'/465, l='MpServer', x=181.95, y=54.56, z=-5.50], we['Zombie'/1237, l='MpServer', x=212.28, y=12.51, z=-13.84], vt['Guardian'/1248, l='MpServer', x=102.50, y=57.28, z=62.50], tx['Squid'/493, l='MpServer', x=203.54, y=61.84, z=-18.44], tx['Squid'/494, l='MpServer', x=207.20, y=62.53, z=-17.79], tx['Squid'/495, l='MpServer', x=211.07, y=62.36, z=-18.03], tx['Squid'/497, l='MpServer', x=203.62, y=61.12, z=-24.51], vt['Guardian'/1271, l='MpServer', x=113.50, y=48.28, z=54.50], vt['Guardian'/1275, l='MpServer', x=117.59, y=48.84, z=54.08]]
	Retry entities: 0 total; []
	Server brand: CanaryMod
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bdb.a(SourceFile:309)
	at ave.b(SourceFile:2293)
	at ave.a(SourceFile:334)
	at net.minecraft.client.main.Main.main(SourceFile:124)

-- System Details --
Details:
	Minecraft Version: 1.8.7
	Operating System: Linux (i386) version 3.13.0-53-generic
	CPU: 4x Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
	Java Version: 1.8.0_20, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Server VM (mixed mode), Oracle Corporation
	Memory: 109721112 bytes (104 MB) / 287064064 bytes (273 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 5 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8.7
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2 GL version 3.0 Mesa 10.1.3, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by 14mRh4X0r** [comment]
I'm not an expert in server texture packs, but this doesn't sound like a canary issue to me. Have you tested this with a vanilla server?

**Comment by walterhiggins** [comment]
Just tested with Vanilla MC. It happens there too. Closing this as it's not a CanaryMod issue.
